apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.mysqlRootPassword | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
