apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          - path: /auth/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.gateway.name }}
                port:
                  number: {{ .Values.gateway.servicePort }}
          - path: /user/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.gateway.name }}
                port:
                  number: {{ .Values.gateway.servicePort }}
          - path: /tasks/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.gateway.name }}
                port:
                  number: {{ .Values.gateway.servicePort }}
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.todoFe.name }}
                port:
                  number: {{ .Values.todoFe.servicePort }}
