apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.taskService.name }}
spec:
  replicas: {{ .Values.taskService.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.taskService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.taskService.name }}
    spec:
      containers:
        - name: {{ .Values.taskService.name }}
          image: "{{ .Values.taskService.image.repository }}:{{ .Values.taskService.image.tag }}"
          ports:
            - containerPort: 3300
              name: gin
          env:
            - name: GIN_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: GIN_PORT_TASK
            - name: GRPC_AUTH_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: GRPC_AUTH_ADDRESS
            - name: GRPC_USER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: GRPC_USER_ADDRESS
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: DB_DSN
              value: root:$(MYSQL_ROOT_PASSWORD)@tcp({{ .Values.mysql.name }}:3306)/todo-task?charset=utf8mb4&parseTime=True&loc=Local
          resources:
            {{- toYaml .Values.taskService.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /ping
              port: 3300
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /ping
              port: 3300
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.taskService.name }}
spec:
  ports:
    - port: {{ .Values.taskService.servicePort.gin }}
      targetPort: 3300
      name: gin
  selector:
    app: {{ .Values.taskService.name }}
